---
title: "data_wrangling_ii"
author: "Rebecca Shyu"
date: "2024-10-10"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(httr)

```

## Reading tables from the web

```{r }

url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html

drug_use_html |>
  html_table()
```

```{r}

table_marj = 
  drug_use_html |> 
  html_table() |> 
  first() |>
  slice(-1)

```

Learning Assessment:

```{r}

cost_of_living = 
  read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") %>% 
  html_table(header=TRUE) %>% 
  first()


```

## CSS Selectors
Star Wars 

selector gadget

```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/") 

swm_title_vec = 
  swm_html %>% 
    html_elements(".ipc-title-link-wrapper .ipc-title__text") %>% 
    html_text()

swm_runtime_vec =  
  swm_html %>% 
    html_elements(".dli-title-metadata-item:nth-child(2)") %>% 
    html_text()

swm_score_vec = 
  swm_html %>% 
  html_elements(".metacritic-score-box") %>% 
  html_text()

```

```{r}
books_html = read_html("https://books.toscrape.com/")

books_html %>% 
  html_elements(".price_color") %>% 
  html_text()
```

Water Consumption API

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content("parsed")
```

BRFSS API
```{r}

brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |> 
  content("parsed")
```

Pokemon API

```{r}
pokemon = 
  GET("http://pokeapi.co/api/v2/pokemon/ditto") |>
  content()

pokemon[["height"]]
pokemon[["abilities"]]

```


